/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jfrlqufqqtsyoobbptob"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcmxxdWZxcXRzeW9vYmJwdG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyOTA0NTEsImV4cCI6MjA4Nzg2NjQ1MX0.B1uJp0oZx3xdbX6Tj2hDaQYh-TcaVu6pMkAUKB4b-zY"